name: Publish-to-APT
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get GPG private key from AWS Secrets Manager
      uses: action-factory/aws-secrets-manager-action@v0.2.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        # Secret will be converted to env var
        secrets: gpg_private_key
        parse_json: false

    - name: Print secret
      run: |
        env

    - name: Push APT_NEW_DEB_PACKAGE to APT repo in S3
      run: |
        docker run -i --privileged \
        -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
        -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
        -e AWS_STORAGE_BUCKET_NAME='nr-repo-apt' \
        -e AWS_S3_MOUNTPOINT='/mnt/aptly' \
        -e APTLY_REPO_NAME='bionic-main' \
        -e APT_NEW_DEB_PACKAGE='' \
        jportasa/aptly-s3fuse:1.0 \
        bash -c """ \
             echo $gpg_private_key > gpg_private_key.gpg; \
             cat gpg_private_key.gpg
        """
#             gpg --allow-secret-key-import gpg_private_key.gpg; \
#             gpg --list-keys
#             && apt-get update \
#             && apt install wget -y \
#             && wget -qO https://download.newrelic.com/infrastructure_agent/linux/apt/pool/main/n/nri-haproxy/nri-haproxy_0.1.0-1_amd64.deb \
#             && aptly repo add ${APTLY_REPO_NAME} ./nri-haproxy_0.1.0-1_amd64.deb \
#             && aptly publish repo $APTLY_REPO_NAME s3:${AWS_APTLY_FRONTEND_STORAGE_NAME}:
#        """







