name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
#  test-go-centos:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Run Go tests in Centos 5
#        run: |
#          docker-compose --file docker-compose-test-centos5.yml run unit
#
#  test-go-windows:
#    runs-on: windows-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Run Go tests in Windows
#        run: |
#          docker-compose --file  docker-compose-test-windows.yml run unit
#
#  test-go-windows:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Run Go tests in Windows
#        run: |
#          docker-compose --file  docker-compose-test-windows.yml run unit

  repo-yum-updater:
    runs-on: ubuntu-latest

    env:
      AWSACCESSKEYID: ${{ secrets.AWSACCESSKEYID }}
      AWSSECRETACCESSKEY: ${{ secrets.AWSSECRETACCESSKEY }}
      AWS_REGION: us-east-1
      REPO_YUM_UPDATE_METADATA_PATH: infrastructure_agent/linux/yum/el/8/x86_64

    steps:
      - uses: actions/checkout@v2

      - name: Start s3fuse & repo-yum-updater
        run: |
          docker-compose --file docker-compose-repo-yum-updater.yml up -d

      - name: Check running containers
        run: docker ps -a

      - name: Stop s3fuse & repo-yum-updater
        run: |
          docker-compose --file docker-compose-repo-yum-updater.yml down